### ISSUE TITLE
HTML Framework

### ISSUE THREAD

**Issue by HarvBCoding** [mateusverbar/gitmeadrink#1]
** Description **

- create header with title
- starter code:
* drown down to return cocktails with certain alcohols

**Comment by mateusverbar** [comment]
I think normally we're supposed to ask for a pull request, and then you would check my code before merging with main, but since we're just setting up a main from which to create a develop branch - I'm just gonna go ahead and close this issue. ("Just gonna go ahead and ..." reminds me of a quote from the movie Office Space.)
